apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-ms-payment-card-checker
  namespace: dev
spec:
  replicas: 1
  revisionHistoryLimit: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: backend-ms-payment-card-checker
  template:
    metadata:
      labels:
        app: backend-ms-payment-card-checker
        version: "1.02"
    spec:
      containers:
        - name: backend-ms-payment-card-checker
          image: qacinescope/qa-backend-ms-payment-card-checker:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "150m"
            limits:
              memory: "150Mi"
              cpu: "350m"
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: qa-config
            - secretRef:
                name: qa-secret
